#!/bin/bash
#SBATCH -t 4:00:00
#SBATCH --ntasks=302
#SBATCH --job-name=ARCTIC
#SBATCH --account=akwaters
#SBATCH --output=ARCTIC.%j
#SBATCH --no-requeue
#SBATCH -p t1standard
###SBATCH -p debug
###SBATCH -t 44:00:00

cd $SLURM_SUBMIT_DIR
. /usr/share/Modules/init/bash
module purge
module load slurm/22.05.4
#module load intel/2023a
module load foss/2022a
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/kshedstrom/intel_23/lib
module load netCDF-Fortran/4.5.4
#module list

#rm ocean.stats.intel* seaice.stats.intel
rm ocean.stats.gnu* seaice.stats.gnu
#
#  Prolog
#
echo " "
echo "++++ Chinook ++++ $PGM_NAME began:    `date`"
echo "++++ Chinook ++++ $PGM_NAME hostname: `hostname`"
echo "++++ Chinook ++++ $PGM_NAME uname -a: `uname -a`"
echo "++++ Chinook ++++ Gnu universe"
echo " "
TBEGIN=`echo "print time();" | perl`

#mpirun -np $SLURM_NTASKS /import/c1/AKWATERS/kshedstrom/MOM6_22/build/intel/bgc_SIS2/repro/MOM6
mpirun -np $SLURM_NTASKS --mca mpi_paffinity_alone 1 /import/c1/AKWATERS/kshedstrom/MOM6_22/build/gnu/bgc_SIS2/repro/MOM6

#
#  Epilog
#
TEND=`echo "print time();" | perl`
echo " "
echo "++++ Chinook ++++ $PGM_NAME pwd:      `pwd`"
echo "++++ Chinook ++++ $PGM_NAME ended:    `date`"
echo "++++ Chinook ++++ $PGM_NAME walltime: `expr $TEND - $TBEGIN` seconds"
