#!/bin/bash
#SBATCH -t 48:00:00
#SBATCH --ntasks=400
#SBATCH --job-name=ARCTIC
#SBATCH --account=akwaters
#SBATCH --output=ARCTIC.%j
#SBATCH --no-requeue
#SBATCH -p t1standard
###SBATCH -p debug
###SBATCH --ntasks=309
###SBATCH -t 44:00:00

cd $SLURM_SUBMIT_DIR
. /usr/share/Modules/init/bash
module purge
module load slurm/22.05.4
module load foss/2022a
module load netCDF-Fortran/4.5.4
#module list

rm ocean.stats.gnu* seaice.stats.gnu
#
#  Prolog
#
echo " "
echo "++++ Chinook ++++ $PGM_NAME began:    `date`"
echo "++++ Chinook ++++ $PGM_NAME hostname: `hostname`"
echo "++++ Chinook ++++ $PGM_NAME uname -a: `uname -a`"
echo " "
TBEGIN=`echo "print time();" | perl`

mpirun -np $SLURM_NTASKS --mca mpi_paffinity_alone 1 /import/c1/AKWATERS/kshedstrom/MOM6_22/build/gnu/SYM_ice_ocean_SIS2/repro/MOM6
#mpirun -np $SLURM_NTASKS --mca mpi_paffinity_alone 1 /import/c1/AKWATERS/kshedstrom/MOM6_22/build/gnu/SYM_ice_ocean_SIS2/debug/MOM6

#
#  Epilog
#
TEND=`echo "print time();" | perl`
echo " "
echo "++++ Chinook ++++ $PGM_NAME pwd:      `pwd`"
echo "++++ Chinook ++++ $PGM_NAME ended:    `date`"
echo "++++ Chinook ++++ $PGM_NAME walltime: `expr $TEND - $TBEGIN` seconds"
