#! /bin/bash

mkdir -p /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/Arctic_12k
cp /autofs/ncrc-svm1_home2/Katherine.Hedstrom/ESMG/ESMG-configs/Arctic6/mid_12/{data_table,diag_table,field_table,input.nml,MOM*,SIS*,run_c6.sub} /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/Arctic_12k

mkdir -p /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/Arctic_12k/INPUT
mkdir -p /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/Arctic_12k/RESTART

pushd /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/Arctic_12k/INPUT
for file in /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/*
do
 ln -sf ${file} .
done
for file in /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/tidal_bcs/*
do
 ln -sf ${file} .
done
ln -sf /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/initial/ice_mass_12k.nc .
ln -sf /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/initial/glorys_ic_75z_1993.nc .
for file in /gpfs/f6/ira-cefi/world-shared/ARC12_pub/GRID/*
do
 ln -sf ${file} .
done

fyear=1993
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/psl_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010000-${fyear}12312100.padded.nc JRA_psl.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/tas_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010000-${fyear}12312100.padded.nc JRA_tas.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/huss_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010000-${fyear}12312100.padded.nc JRA_huss.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/uas_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010000-${fyear}12312100.padded.nc JRA_uas.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/vas_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010000-${fyear}12312100.padded.nc JRA_vas.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/rlds_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010130-${fyear}12312230.padded.nc JRA_rlds.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/rsds_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010130-${fyear}12312230.padded.nc JRA_rsds.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/prra_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010130-${fyear}12312230.padded.nc JRA_prra.nc
ln -sf /gpfs/f6/gfdl/world-shared/gold/datasets/reanalysis/JRA55-do/v1.5.0/padded/prsn_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-5-0_gr_${fyear}01010130-${fyear}12312230.padded.nc JRA_prsn.nc

ln -sf /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/Runoff/glofas_hill_${fyear}_Ob_pur_mez.nc glofas_runoff.nc
for file in /gpfs/f6/ira-cefi/world-shared/ARC12_pub/ESMG/INPUT/obc/${fyear}/*
do
 ln -sf ${file} .
done

ln -sf /gpfs/f6/ira-cefi/world-shared/ARC12_pub/share/restrat_vars_81.nc .

cd ..
sbatch run_c6.sub
