#!/bin/bash

#SBATCH -n 452
## if you prefer to specify nodes, use instead:
##SBATCH -N 10
#SBATCH --time=1:00:00
#SBATCH --job-name="Arctic"
#SBATCH --output=Arctic_o.%j
#SBATCH --error=Arctic_e.%j
#SBATCH --qos=normal
#SBATCH --partition=batch
#SBATCH --clusters=c6
## obviously use your group account:
#SBATCH --account=ira-cefi

rm -f *.stats.intel

srun -n 452 /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/ESMG_build//intel/SYM_ice_ocean_SIS2/repro/MOM6
#srun -n 452 /gpfs/f6/ira-cefi/scratch/Katherine.Hedstrom/ESMG_build//intel/SYM_ice_ocean_SIS2/debug/MOM6
